config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: "edit"
  patch "tasks/:id", to: "tasks#update"
  get "tasks/:id", to: "tasks#show", as: "task"
  delete "tasks/:id", to: "tasks#destroy", as: "delete"


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params

      params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task</h1>
  <%= form_with model: @task do |f| %>
    <%= f.label :title, {:class => "form-label"} %>
    <%= f.text_field :title, {:class => "form-control mb-3"} %>
    <%= f.label :details, {:class => "form-label"} %>
    <%= f.text_area :details, {:class => "form-control mb-3"} %>
    <%= f.check_box :completed, {}, true, false %>
    <%= f.label "Completed?", {:class => "form-label"} %>
    <br>
    <%= f.submit :class => "btn btn-primary my-3" %>
  <% end %>
  <%= link_to tasks_path, :class => "text-decoration-none" do %>
    <i class="fa-solid fa-rotate-left"></i>
    Back to list
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
    <h1>My Tasks</h1>
    <ul>
         <% @tasks.each do |task| %>
        <div class="d-flex">
        <%= form_with model: task do |f| %>
                    <%= f.check_box :completed, {}, true, false %>
                <% end %>
                <%= link_to task.title, task_path(task.id), :class => "text-decoration-none px-2" %>
                <%= link_to delete_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "px-2" do %>
                    <i class="fa-solid fa-trash"></i>
                <% end %>
        </div>
        <% end %>
    </ul>
    <hr>
    <%= link_to "#{tasks_path}/new", :class => "text-decoration-none" do %>
        <i class="fa-solid fa-plus"></i> Add a new task
    <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 >Create Task</h1>
  <%= form_with model: @task do |f| %>
    <%= f.label :title, {:class => "form-label"} %>
    <%= f.text_field :title, {:class => "form-control mb-3"} %>
    <%= f.label :details, {:class => "form-label"} %>
    <%= f.text_area :details, {:class => "form-control mb-3"} %>
    <%= f.submit :class => "btn btn-primary my-3" %>
  <% end %>
  <%= link_to tasks_path, :class => "text-decoration-none" do %>
    <i class="fa-solid fa-rotate-left"></i>
    Back to list
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
    <div class="d-flex justify-content-between p-3">
        <h2><%= @task.title %></h2>
        <div class="p-2 border">
            <%= link_to edit_path(@task.id), {:class => "text-decoration-none"} do %>
            <i class="fa-solid fa-pen"></i> Edit this task
            <% end %>
        </div>
    </div>
    <div class="p-4 border border-primary-subtle bg-secondary-subtle rounded-3"><%= @task.details %></div>
    <div class="py-4">
        <%= form_with model: @task do |f| %>
            <%= f.check_box :completed, {}, true, false %>
            <%= f.label "completed"%>
            <%# add logic to label check box %>
        <% end %>
    </div>
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-rotate-left"></i>
    Back to list
  <% end %>
</div>